//
//  ContactExample.swift
//  Smart Migration
//
//  Created by Jan Janovec on 27.10.2022.
//

import Foundation
import MapKit

struct ContactExample: Hashable{
    var name: String
    var phoneNumber: Int
    var description: String
    var address: Address
    var email: String
    var website: String
}

struct Address: Hashable {
    
    
    var streetName: String
    var streetNumber: String
    var cityName: String
    var state: String
    var postalCode: Int
    
    var coordinates: CLLocationCoordinate2D
}

class ContactList{
    
    
    var contacts = Array(Set([
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úřad se stará o migranty, kteří přijeli do ČR z cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195021, longitude: 16.60623)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Усі події в Україні та світі за останній час, найголовніше, огляди", phoneNumber: 123412321, description: "Migrační úřad se stará o migranty, kteří přijeli do ČR z ciafdsdfsafzí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.606836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úřad se stará o migranty, kteří přijeli do ČR z cizí země Lorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero.", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.606836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Integration centre Jihlava - Centre for Support of Integration of Foreigners (CPIC)", phoneNumber: 123412321, description: "Migrační úřad se stará o migranty,fdsadfs kteří fpřijeli do ČR z cizí země", address: Address(streetName: "PalackéLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero.ho", streetNumber: "23", cityName: "Jihlava", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.3333, longitude: 15.5833)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úřad se starfá o migranty, kteří přijeli do ČR z cizí zLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero.emě", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.66836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úřad se starfáfd o migranty, kteří přijeli do Lorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero.ČR z cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.6206836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Integration centre Jihlava - Centre for Support of Integration of Foreigners (CPIC)", phoneNumber: 123412321, description: "Migrační úřad se stará o migranty, kteří přijelai do ČR z cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.6206836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úřad se stará o migranty, kteří přijeli do ČR zLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero. cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195021, longitude: 16.60623)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Усі події в Україні та світі за останній час, найголовніше, огляди", phoneNumber: 123412321, description: "MLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero.igrační úřad se stará o migranty, kteří přijeli do ČR z ciafdsdfsafzí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.606836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úřad se stará o migranty, kteří přijeli do ČRLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero. z cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.606836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Integration centre Jihlava - Centre for Support of Integration of Foreigners (CPIC)", phoneNumber: 123412321, description: "Migrační úřad se stará o migranty,fdsadfs kteří fpřijeli do ČR z cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Jihlava", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.3333, longitude: 15.5833)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úřad se starfá o migranty, kteří přijeli do ČLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero.R z cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.66836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero.řad se starfáfd o migranty, kteří přijeli do ČR z cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.6206836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Integration centre Jihlava - Centre for Support of Integration of Foreigners (CPIC)", phoneNumber: 123412321, description: "Migrační úřad se stará oLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero. migranty, kteří přijelai do ČR z cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.6206836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úřaLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero.d se stará o migranty, kteří přijeli do ČR z cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195021, longitude: 16.60623)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Усі події в Україні та світі за останній час, найголовніше, огляди", phoneNumber: 123412321, description: "MigračLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero.ní úřad se stará o migranty, kteří přijeli do ČR z ciafdsdfsafzí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.606836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úřad se stará o migranty, kteří přijeli do ČR zLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero. cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.606836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Integration centre Jihlava - Centre for Support of Integration of Foreigners (CPIC)", phoneNumber: 123412321, description: "Migrační úřad se stará o migranty,fdsadfs kteří fpřijeli do ČR z cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Jihlava", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.3333, longitude: 15.5833)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úřad se starfá o migranty, kteří přijeli do ČR z cizí zLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero.emě", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.66836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero.řad se starfáfd o migranty, kteří přijeli do ČR z cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.6206836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Integration centre Jihlava - Centre for Support of Integration of Foreigners (CPIC)", phoneNumber: 123412321, description: "Migrační úřad se stará o migranty, kteříLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero. přijelai do ČR z cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.6206836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úřad se sLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero.tará o migranty, kteří přijeli do ČR z cizí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195021, longitude: 16.60623)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Усі події в Україні та світі за останній час, найголовніше, огляди", phoneNumber: 123412321, description: "Migrační úřad se stará o migranty, kteří přLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero.ijeli do ČR z ciafdsdfsafzí země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.606836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Migrační úřad Brno", phoneNumber: 123412321, description: "Migrační úřad se stará o migranty, kteří přijeli do ČR z cizíLorem ipsum dolor sit amet, consectetuer adipiscing elit. In dapibus augue non sapien. Nam quis nulla. Sed ac dolor sit amet purus malesuada congue. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Nullam faucibus mi quis velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nunc tincidunt ante vitae massa. Nam sed tellus id magna elementum tincidunt. Aliquam erat volutpat. Nulla est. Nullam dapibus fermentum ipsum. Nullam rhoncus aliquam metus. Maecenas libero. země", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Brno", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.195061, longitude: 16.606836)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    ContactExample(name: "Integration centre Jihlava - Centre for Support of Integration of Foreigners (CPIC)", phoneNumber: 123412321, description: "ahoj", address: Address(streetName: "Palackého", streetNumber: "23", cityName: "Jihlava", state: "Czech republic", postalCode: 60200, coordinates: CLLocationCoordinate2D(latitude: 49.3333, longitude: 15.5833)), email: "icijihlava@suz.cz", website: "http://www.integracnicentra.cz/jihlava"),
                    
    ]))
}

//cite
extension CLLocationCoordinate2D: Hashable {
    public static func == (lhs: Self, rhs: Self) -> Bool {
        return lhs.latitude == rhs.latitude && lhs.longitude == rhs.longitude
    }
    
    public func hash(into hasher: inout Hasher) {
        hasher.combine(latitude)
        hasher.combine(longitude)
    }
}
