//
//  IssueExample.swift
//  Smart Migration
//
//  Created by Jan Janovec on 02.11.2022.
//

import Foundation
import SwiftUI

struct IssueExample: Hashable{
    
    var title: String
    var posted: Date
    var image: Image?
    var content: String
    var website: String
    
    var relatedContacts: [ContactExample]
    var tags: [TagExample]
    var tasks: [TaskExample]
    
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(content)
    }
}


struct IssueExapmles {
    
    let issues: [IssueExample] = Array(Set([
        IssueExample(title: "What I have to do first in the Czech Republic? How to register and to get a support?", posted: Date.now, content: "Welcome to the Czech Republic! Welcome to the Czech Republic! Welcome to the Czech Republic! Welcome to the Czech Republic! ", website: "http://www.integracnicentra.cz/jihlava", relatedContacts: [ContactList().contacts[0], ContactList().contacts[1]], tags: [TagExample(name: "start", color: "Red"), TagExample(name: "Czech republic", color: "Blue"), TagExample(name: "Passport", color: "Yellow")], tasks: [TaskExample(text: "Get a passport", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean id metus id velit ullamcorper pulvinar. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Aliquam erat volutpat. Nulla quis diam. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Etiam neque. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.", index: 0), TaskExample(text: "welcome", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean id metus id velit ullamcorper pulvinar. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Aliquam erat volutpat. Nulla quis diam. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Etiam neque. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.", index: 1)]),
        IssueExample(title: "How to register and to get a support?", posted: Date.now, content: "Welcome to the Czech Republic! Welcome to the Czech epubic! Welcome to the Czech Republic! Welcome to the Czech Republic! ", website: "http://www.integracnicentra.cz/jihlava", relatedContacts: [ContactList().contacts[0], ContactList().contacts[1]], tags: [TagExample(name: "start", color: "Red"), TagExample(name: "Czech republic", color: "Blue"), TagExample(name: "Passport", color: "Yellow")], tasks: [TaskExample(text: "Get a passport", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean id metus id velit ullamcorper pulvinar. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Aliquam erat volutpat. Nulla quis diam. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Etiam neque. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.", index: 0), TaskExample(text: "welcome", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean id metus id velit ullamcorper pulvinar. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Aliquam erat volutpat. Nulla quis diam. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Etiam neque. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.", index: 1)]),
        IssueExample(title: "How to register and to get a support?", posted: Date.now, content: "Welcome to the Czech Republic! Welcome to the Czech epblic! Welcome to the Czech Republic! Welcome to the Czech Republic! ", website: "http://www.integracnicentra.cz/jihlava", relatedContacts: [ContactList().contacts[0], ContactList().contacts[1]], tags: [TagExample(name: "start", color: "Red"), TagExample(name: "Czech republic", color: "Blue"), TagExample(name: "Passport", color: "Yellow")], tasks: [TaskExample(text: "Get a passport", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean id metus id velit ullamcorper pulvinar. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Aliquam erat volutpat. Nulla quis diam. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Etiam neque. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.", index: 0), TaskExample(text: "welcome", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean id metus id velit ullamcorper pulvinar. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Aliquam erat volutpat. Nulla quis diam. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Etiam neque. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.", index: 1)]),
        IssueExample(title: "How to register and to get a support?", posted: Date.now, content: "Welcome to the Czech Republic! Welcome to the Czecfdsh epublic! Welcome to the Czech Republic! Welcome to the Czech Republic! ", website: "http://www.integracnicentra.cz/jihlava", relatedContacts: [ContactList().contacts[0], ContactList().contacts[1]], tags: [TagExample(name: "start", color: "Red"), TagExample(name: "Czech republic", color: "Blue"), TagExample(name: "Passport", color: "Yellow")], tasks: [TaskExample(text: "Get a passport", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean id metus id velit ullamcorper pulvinar. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Aliquam erat volutpat. Nulla quis diam. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Etiam neque. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.", index: 0), TaskExample(text: "welcome", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean id metus id velit ullamcorper pulvinar. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Aliquam erat volutpat. Nulla quis diam. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Etiam neque. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.", index: 1)]),
        IssueExample(title: "How to register and to get a support?", posted: Date.now, content: "Welcome to the Czech Republic! Welcome to the Czech epublic! Welcome to thafde Czech Republic! Welcome to the Czech Republic! ", website: "http://www.integracnicentra.cz/jihlava", relatedContacts: [ContactList().contacts[0], ContactList().contacts[1]], tags: [TagExample(name: "start", color: "Red"), TagExample(name: "Czech republic", color: "Blue"), TagExample(name: "Passport", color: "Yellow")], tasks: [TaskExample(text: "Get a passport", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean id metus id velit ullamcorper pulvinar. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Aliquam erat volutpat. Nulla quis diam. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Etiam neque. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.", index: 0), TaskExample(text: "welcome", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean id metus id velit ullamcorper pulvinar. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Aliquam erat volutpat. Nulla quis diam. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Etiam neque. Mauris dolor felis, sagittisfdas at, luctus sed, aliquam non, tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.", index: 1)])
    ]))
    
}
